export const CATEGORIES = ['blouse', 'dress', 'shirt', 'accessory', 'skirt', 'robe'];

const PRODUCTS = [
  {
    id: '1',
    nameEn: 'Classic Silk Blouse',
    nameEs: 'Blusa de Seda Clásica',
    category: 'blouse',
    price: 189,
    currency: 'USD',
    material: '100% Mulberry Silk',
    colors: ['Ivory', 'Blush', 'Navy'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: ['https://source.unsplash.com/featured/600x800/?silk,blouse,fabric'],
    descriptionEn: 'Timeless elegance meets modern sophistication in this luxurious silk blouse. Crafted from 100% premium mulberry silk.',
    descriptionEs: 'Elegancia atemporal en esta lujosa blusa de seda mulberry 100% pura.',
    featured: true,
  },
  {
    id: '2',
    nameEn: 'Evening Silk Dress',
    nameEs: 'Vestido de Seda de Noche',
    category: 'dress',
    price: 349,
    currency: 'USD',
    material: '100% Mulberry Silk',
    colors: ['Midnight', 'Champagne', 'Crimson'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: ['https://source.unsplash.com/featured/600x800/?silk,dress,textile'],
    descriptionEn: 'An exquisite evening dress that flows with graceful movement, made from the finest mulberry silk.',
    descriptionEs: 'Un exquisito vestido de noche que fluye con movimiento elegante.',
    featured: true,
  },
  {
    id: '3',
    nameEn: 'Luxury Silk Scarf',
    nameEs: 'Pañuelo de Seda de Lujo',
    category: 'accessory',
    price: 89,
    currency: 'USD',
    material: '100% Mulberry Silk',
    colors: ['Gold', 'Onyx', 'Sapphire'],
    sizes: ['One Size'],
    images: ['https://source.unsplash.com/featured/600x800/?silk,scarf,luxury'],
    descriptionEn: 'A versatile accessory crafted from premium silk, adding elegance to any outfit.',
    descriptionEs: 'Un accesorio versátil de seda premium que añade elegancia a cualquier atuendo.',
    featured: true,
  },
  {
    id: '4',
    nameEn: "Men's Silk Shirt",
    nameEs: 'Camisa de Seda para Hombre',
    category: 'shirt',
    price: 229,
    currency: 'USD',
    material: '100% Mulberry Silk',
    colors: ['Ivory', 'Slate', 'Sage'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: ['https://source.unsplash.com/featured/600x800/?silk,shirt,fabric'],
    descriptionEn: 'Refined and sophisticated, this silk shirt is perfect for any occasion.',
    descriptionEs: 'Refinada y sofisticada, esta camisa de seda es perfecta para cualquier ocasión.',
    featured: true,
  },
  {
    id: '5',
    nameEn: 'Silk Wrap Skirt',
    nameEs: 'Falda Envolvente de Seda',
    category: 'skirt',
    price: 165,
    currency: 'USD',
    material: '100% Mulberry Silk',
    colors: ['Gold', 'Cream', 'Tan'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: ['https://source.unsplash.com/featured/600x800/?silk,skirt,textile'],
    descriptionEn: 'A flowing wrap skirt in premium silk that drapes beautifully.',
    descriptionEs: 'Una falda envolvente de seda premium con una caída hermosa.',
    featured: false,
  },
  {
    id: '6',
    nameEn: 'Silk Kimono Robe',
    nameEs: 'Bata Kimono de Seda',
    category: 'robe',
    price: 195,
    currency: 'USD',
    material: '100% Mulberry Silk',
    colors: ['Ivory', 'Gold', 'Cobalt'],
    sizes: ['S/M', 'L/XL'],
    images: ['https://source.unsplash.com/featured/600x800/?kimono,silk,robe'],
    descriptionEn: 'A luxurious kimono robe crafted from pure mulberry silk for ultimate comfort.',
    descriptionEs: 'Una lujosa bata kimono de seda mulberry pura para el máximo confort.',
    featured: false,
  },
  {
    id: '7',
    nameEn: 'Silk Evening Gown',
    nameEs: 'Vestido de Gala de Seda',
    category: 'dress',
    price: 485,
    currency: 'USD',
    material: '100% Mulberry Silk',
    colors: ['Onyx', 'Bordeaux', 'Champagne'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: ['https://source.unsplash.com/featured/600x800/?gown,silk,evening'],
    descriptionEn: 'A stunning evening gown that embodies the pinnacle of silk craftsmanship.',
    descriptionEs: 'Un impresionante vestido de gala que encarna el pináculo de la artesanía en seda.',
    featured: false,
  },
  {
    id: '8',
    nameEn: 'Silk Pajama Set',
    nameEs: 'Conjunto de Pijama de Seda',
    category: 'robe',
    price: 275,
    currency: 'USD',
    material: '100% Mulberry Silk',
    colors: ['Sage', 'Ivory', 'Midnight'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: ['https://source.unsplash.com/featured/600x800/?silk,pajama,fabric'],
    descriptionEn: 'Indulge in the ultimate luxury of a pure silk pajama set.',
    descriptionEs: 'Disfruta del lujo supremo de un conjunto de pijama de seda pura.',
    featured: false,
  },
];

export function getProducts(category) {
  if (!category || category === 'all') return PRODUCTS;
  return PRODUCTS.filter(p => p.category === category);
}

export function getFeaturedProducts() {
  return PRODUCTS.filter(p => p.featured);
}

export function getProductById(id) {
  return PRODUCTS.find(p => p.id === String(id)) || null;
}
